//! Public plugin API for LoomChart.
//!
//! Plugin authors depend on this crate and implement the traits here.
//! The host (chartcore) loads compiled .wasm binaries and calls the exported
//! functions generated by the `#[loomchart_plugin]` macro from `loom-plugin-sdk`.
//!
//! # Protocol
//!
//! Each plugin WASM binary must export these C-ABI functions:
//!
//! - `loom_manifest(out_ptr: *mut u8, out_cap: usize) -> usize`
//!   Write JSON-encoded `PluginManifest` into out_ptr, return byte count.
//!
//! - `loom_inputs(out_ptr: *mut u8, out_cap: usize) -> usize`
//!   Write JSON-encoded `Vec<InputConfig>` into out_ptr, return byte count.
//!
//! - `loom_plots(out_ptr: *mut u8, out_cap: usize) -> usize`
//!   Write JSON-encoded `Vec<PlotConfig>` into out_ptr, return byte count.
//!
//! - `loom_calculate(ctx_ptr: *const u8, ctx_len: usize, out_ptr: *mut u8, out_cap: usize) -> usize`
//!   Read JSON-encoded `CalculationRequest` from ctx_ptr/ctx_len,
//!   write JSON-encoded `CalculationResponse` into out_ptr, return byte count.
//!
//! - `loom_reset()`
//!   Reset internal state (called between backtest runs etc.)
//!
//! - `loom_alloc(size: usize) -> *mut u8`
//!   Allocate a buffer inside plugin memory (host uses this to write inputs).
//!
//! - `loom_dealloc(ptr: *mut u8, size: usize)`
//!   Free a buffer allocated with `loom_alloc`.

pub mod manifest;
pub mod types;
pub mod traits;

pub use manifest::{Capability, PluginManifest, PluginType};
pub use traits::{DataSourcePlugin, IndicatorPlugin, RendererPlugin, StrategyPlugin};
pub use types::{
    Candle, Color, InputConfig, InputType, InputValue, PlotConfig, PlotStyle, RenderCommand,
    Signal, SignalKind, SourceType,
};
