-- Migration: Create signals table
-- Description: Trading signals for future use (buy/sell markers)

CREATE TABLE IF NOT EXISTS signals (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    source TEXT NOT NULL,
    symbol TEXT NOT NULL,
    timeframe TEXT NOT NULL CHECK (timeframe IN ('1m', '5m', '15m', '30m', '1h', '4h', '1d', '1w')),
    ts TIMESTAMPTZ NOT NULL,
    signal_type TEXT NOT NULL CHECK (signal_type IN ('buy', 'sell', 'exit', 'alert')),
    strategy TEXT,
    price NUMERIC,
    confidence NUMERIC CHECK (confidence >= 0 AND confidence <= 1),
    metadata JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    UNIQUE (source, symbol, timeframe, ts, signal_type, strategy)
);

-- Index for signal lookup
CREATE INDEX IF NOT EXISTS idx_signals_lookup
ON signals (source, symbol, timeframe, ts DESC);

-- Index for strategy filtering
CREATE INDEX IF NOT EXISTS idx_signals_strategy
ON signals (strategy, ts DESC);

-- Comments
COMMENT ON TABLE signals IS 'Trading signals generated by strategies (for backtesting/live trading)';
COMMENT ON COLUMN signals.confidence IS 'Signal confidence score between 0 and 1';
